package(default_visibility = ["//visibility:public"])

filegroup(
    name = "debug_dashboard_html",
    srcs = ["debug_dashboard.html"],
)

filegroup(
    name = "dashboard_html",
    srcs = ["dashboard.html"],
)

exports_files([
    "debug_dashboard.html",
    "dashboard.html",
])
